# Generated by Django 5.0.6 on 2024-10-02 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_read_by_book_read_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='read_by',
            field=models.ManyToManyField(related_name='read_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
