# Generated by Django 5.1.2 on 2024-10-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_read_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='literary_genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
