# Generated by Django 5.1.4 on 2024-12-14 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_author_alt_name_alter_author_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='alt_name',
            new_name='altName',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='full_name',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='literary_genre',
            new_name='literaryGenre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='literary_type',
            new_name='literaryType',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publish_year',
            new_name='publishYear',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='titleName',
        ),
        migrations.RemoveField(
            model_name='book',
            name='read_by',
        ),
        migrations.AddField(
            model_name='book',
            name='readBy',
            field=models.ManyToManyField(blank=True, related_name='readBooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
