# Generated by Django 5.1.4 on 2024-12-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_rename_alt_name_author_altname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='altName',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
