# Generated by Django 5.1.2 on 2025-01-14 23:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_author_altname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='altName',
            new_name='alt_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='fullName',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='literaryGenre',
            new_name='literary_genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='literaryType',
            new_name='literary_type',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publishYear',
            new_name='publish_year',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='titleName',
            new_name='title_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='readBy',
        ),
        migrations.AddField(
            model_name='book',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
